name: "Donation Service - Build & Deploy"

on:
  push:
    branches: [main]
    paths: ["donation-service/**"]
  pull_request:
    branches: [main]
    paths: ["donation-service/**"]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_ci-go.yml
    with:
      service_name: donation-service
      go_version: "1.21"

  build:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_build-push-ocir.yml
    with:
      service_name: donation-service
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy-oke.yml
    with:
      service_name: donation-service
      db_init_wait_job: db-init-donation
    secrets: inherit
