name: "Flag Service - Build & Deploy"

on:
  push:
    branches: [main]
    paths:
      - "flag-service/**"
  pull_request:
    branches: [main]
    paths:
      - "flag-service/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/reusable-python-service.yml
    with:
      service_name: flag-service
    secrets:
      OCI_REGION: ${{ secrets.OCI_REGION }}
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      OCI_TENANCY_NAMESPACE: ${{ secrets.OCI_TENANCY_NAMESPACE }}
      OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
